author: Marco Santarossa
author_url: http://marcosantadev.com/
github_url: https://github.com/MarcoSantarossa/MSUITest
root_url: https://marcosantarossa.github.io/MSUITest/
module: MSUITest
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'MSUITest.xcworkspace', -scheme, 'MSUITest']