opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - first_where
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - lower_acl_than_parent
  - last_where
  - legacy_random
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - void_return
  - yoda_condition


disabled_rules:
  - identifier_name
  - force_try
  - line_length
  - file_length
  - force_cast
  - function_body_length
  - type_body_length
  - xctfail_message
  - cyclomatic_complexity

function_parameter_count: 7

empty_count:
  severity: warning

nesting:
  type_level:
    warning: 2
